### ISSUE TITLE
Brightness/lightlevels changes/are not persistent through conversion

### ISSUE THREAD

**Issue by AtlasRedux** [francescofugazzi/3dgsconverter#4]
Brightness/lightlevels change when converting. It's not majorly obvious at first glance, but it's there.

Example: https://i.imgur.com/sS3Xn6a.jpg

**Comment by francescofugazzi** [comment]
That's weird... the values don't get changed at all as the values just get copied. Did you import the CC version in Unreal? The CC version with --rgb flag has vertex colors in addition to the other values and I made it only for having a content reference in cloud compare for editing. If you convert from original 3dgs to cc and then from cc to 3dgs you obtain an identical file 1:1 with the same md5. Could you please provide me more details?

**Comment by AtlasRedux** [comment]
*shrug*
Must be something when editing it that changes the looks in UE or something. I have no idea. Guess it's not a conversion issue then.
