### ISSUE TITLE
Changing threshold value doesn't work

### ISSUE THREAD

**Issue by bmikaili** [francescofugazzi/3dgsconverter#6]
For me, there's no change when changing threshold values. Anyone else have this issue?

**Comment by xuxumiao777** [comment]
@bmikaili maybe you need to reinstall the library again.

**Comment by francescofugazzi** [comment]
@bmikaili i just updated (after long time) the code and the parameters aren't ingored anymore. It was a mistake I made when refactoring the code and the custom values where ignored, only the hardcoded ones were working
